### ISSUE TITLE
Why my training curve so non-stationary?

### ISSUE THREAD

**Issue by Amanda2024** [seungeunrho/football-paris#2]
Hi, I had run your code without any modification, but I got the following result.
 
![image](https://user-images.githubusercontent.com/28642602/102155247-22939780-3eb6-11eb-9bb1-4c4df493b1f0.png)

**Comment by glooomymonday** [comment]
Could you please elaborate which part do you think it is non-stationary?

**Comment by Amanda2024** [comment]
Thanks for your reply to me. Maybe the training time is too short the winrate curve. I trained for longer and it becomed stationary.
On 12/29/2020 00:54，glooomymonday<notifications@github.com> wrote：

Could you please elaborate which part do you think it is non-stationary?
